zoom_out:
  base: ""
  lora: ""

  init_image: "__assets__/ipadapter/An_astronaut_is_riding_a_horse_on_Mars_seed-444264997.png"
  denoise_strength: 0.84

  motion_module_lora_configs:
    - path:  "models/MotionLoRA/v2_lora_ZoomOut.ckpt"
      alpha: 1.0

  enable_ipadapter: true
  ip_strength: 1

  enable_controlnet: true
  controlnet_name: control_v11p_sd15_canny
  controlnet_image: "__assets__/images_with_control/astronaut_canny.png"

  motion_module:
    - "models/Motion_Module/mm_sd_v15_v2.ckpt"

  seed:           [444264997]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "An astronaut is riding a horse on Mars"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"
zoom_in:
  base: ""
  lora: ""

  init_image: "__assets__/ipadapter/An_astronaut_is_riding_a_horse_on_Mars_seed-444264997.png"
  denoise_strength: 0.84

  motion_module_lora_configs:
    - path:  "models/MotionLoRA/v2_lora_ZoomOut.ckpt"
      alpha: 1.0

  enable_ipadapter: true
  ip_strength: 1

  enable_controlnet: true
  controlnet_name: control_v11p_sd15_canny
  controlnet_image: "__assets__/images_with_control/astronaut_canny.png"

  motion_module:
    - "models/Motion_Module/mm_sd_v15_v2.ckpt"

  seed:           [444264997]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "An astronaut is riding a horse on Mars"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"