all:
  base: ""
  lora: ""

  init_image: "__assets__/ipadapter/An_astronaut_is_riding_a_horse_on_Mars_seed-444264997.png"
  denoise_strength: 0.84

  enable_ipadapter: true
  ip_strength: 1

  enable_controlnet: true
  controlnet_name: control_v11p_sd15_canny
  controlnet_image: "__assets__/images_with_control/astronaut_canny.png"

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"

  seed:           [444264997]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "An astronaut is riding a horse on Mars"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"
without_denoise:
  base: ""
  lora: ""

  init_image: "__assets__/ipadapter/An_astronaut_is_riding_a_horse_on_Mars_seed-444264997.png"
  denoise_strength: 1

  enable_ipadapter: true
  ip_strength: 1

  enable_controlnet: true
  controlnet_name: control_v11p_sd15_canny
  controlnet_image: "__assets__/images_with_control/astronaut_canny.png"

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"

  seed:           [444264997]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "An astronaut is riding a horse on Mars"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"
without_ipadapter:
  base: ""
  lora: ""

  init_image: "__assets__/ipadapter/An_astronaut_is_riding_a_horse_on_Mars_seed-444264997.png"
  denoise_strength: 0.84

  enable_ipadapter: false
  ip_strength: 1

  enable_controlnet: true
  controlnet_name: control_v11p_sd15_canny
  controlnet_image: "__assets__/images_with_control/astronaut_canny.png"

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"

  seed:           [444264997]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "An astronaut is riding a horse on Mars"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"
without_controlnet:
  base: ""
  lora: ""

  init_image: "__assets__/ipadapter/An_astronaut_is_riding_a_horse_on_Mars_seed-444264997.png"
  denoise_strength: 0.84

  enable_ipadapter: true
  ip_strength: 1

  enable_controlnet: true
  controlnet_name: control_v11p_sd15_canny
  controlnet_image: "__assets__/images_with_control/astronaut_canny.png"

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"

  seed:           [444264997]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "An astronaut is riding a horse on Mars"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"
