test:
  base: ""
  path: ""

  init_image: "__assets__/ipadapter/a_girl_in_the_wind.png"
  denoise_strength: 0.6
  init_alpha: 0.1
  alpha_step: 0.01
  truncate_alpha: 0.05

  IPAdapter: true
  ip_strength: 1

  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  seed:           [-1]
  steps:          25
  guidance_scale: 7.5
  lora_alpha: 0.8

  prompt:
    - "1girl, solo, shirt, realistic, black hair, looking at viewer, white shirt, collared shirt, smile, closed mouth, lips, portrait, black eyes, head tilt, medium hair, indoors, A girl in the wind，wink, Hair blown by the wind，best quality, high quality"
  n_prompt:
    - "monochrome, lowres, bad anatomy, worst quality, low quality"
